/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

import React, { useMemo } from 'react';
import { EuiToolTip } from '@elastic/eui';
import { i18n } from '@kbn/i18n';
import { UserAvatar } from '@kbn/user-profile-components';

import { useBulkGetUserProfiles } from '../../../../../common/components/user_profiles/use_bulk_get_user_profiles';
import { UNKNOWN_USER_PROFILE_NAME } from '../../../../../common/components/user_profiles/translations';

export const GeneratedByBadge = ({ userId }: { userId: string }) => {
  const uids = useMemo(() => new Set([userId]), [userId]);
  const { data: users } = useBulkGetUserProfiles({ uids });
  const userProfile = users?.[0];

  const tooltipContent = useMemo(() => {
    const displayName = userProfile
      ? userProfile.user.full_name ?? userProfile.user.email ?? userProfile.user.username
      : UNKNOWN_USER_PROFILE_NAME;

    return i18n.translate(
      'xpack.securitySolution.detectionEngine.attacks.tableSection.generatedByTooltipTitle',
      {
        defaultMessage: 'Manually generated by {name}',
        values: { name: displayName },
      }
    );
  }, [userProfile]);

  return (
    <EuiToolTip content={tooltipContent}>
      <div data-test-subj="attack-generated-by-badge">
        <UserAvatar user={userProfile?.user} avatar={userProfile?.data?.avatar} size="s" />
      </div>
    </EuiToolTip>
  );
};
